modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved, Please see homepage."
issueTrackerURL="https://github.com/defeatedcrow/CustomSpawn/issues"
[[mods]]
modId="dcs_custom_spawn"
version="${file.jarVersion}"
displayName="CustomSpawn"
updateJSONURL=""
displayURL="https://github.com/defeatedcrow/CustomSpawn"
logoFile=""
authors="defeatedcrow"

description='''
A mod for customizing mob spawning.
The following spawn bans can be set in the config file:
- Specific altitude
- From the spawner
- Near the village
- Biome Tags
- Block Tags
'''

[[dependencies.dcs_custom_spawn]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="SERVER"
[[dependencies.dcs_custom_spawn]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="SERVER"
